### ISSUE TITLE
Deleting shop logo deletes the shop..

### ISSUE THREAD

**Issue by jaywink** [shoopio/shoop#205] opened 2015-10-04 00:21 UTC
Found a nice bug in current development head, tip of master branch.

If you delete the image set as shop logo, you delete the whole shop... ;)

![recorded](https://cloud.githubusercontent.com/assets/1174866/10265774/d776be42-6a46-11e5-9de4-3481cec15b2f.gif)

**Comment by Pikkupomo** [comment] 2015-10-04 07:30
This issue is caused by `Category` and `Shop` object both missing `on_delete=models.SET_NULL` in their `image` fields. So the issue affects both and fix will come soon.

**Comment by akx** [comment] 2015-10-05 08:07
Good catch, thanks. This is being tracked as SHOOP-1617, being fixed by @Pikkupomo.

**Closed** 2015-10-05 11:18 UTC
Labels: bug

**Comment by jaywink** [comment] 2015-10-05 11:32
Yay, thanks for patching this so fast! :+1:
